name: simple_timetable
description: Simple timetable
version: 0.0.12
homepage: https://github.com/hadukin/simple_timetable
repository: https://github.com/hadukin/simple_timetable

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_date: ^1.0.9
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

flutter:
