name: simple_timetable
description: Simple timetable
version: 1.0.0
homepage: https://github.com/hadukin/simple_timetable
repository: https://github.com/hadukin/simple_timetable

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  dart_date: ^1.1.0-nullsafety.0
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
